@startuml Case View
title Use Case Diagram

actor Player

usecase "Start Game" as UC1
usecase "Fight Enemy" as UC2
usecase "Earn Reward" as UC3
usecase "Buy Item" as UC4

Player --> UC1
Player --> UC2
Player --> UC3
Player --> UC4
@enduml