@startuml Logical View
title Class Diagram

class Game {
  - currentRoom : Room
  - currentLevel : int
  + startGame() : void
  + generateRoom() : Room
}

class Room {
  - name : string
  - type : int
}

class Room_Stage {
  - level : int
  - enemy : Enemy
  - reward : int
}

class Room_Shop {
  - inventory : Item[]
  + buyItem() : void
}

class mob {
  - name : string
  - hp : int
  - attackValue : int
  - defense : int
  - isDead : bool
  + attack() : void
  + die() : void
}

class Player {
  - money : int
  - inventory : Item[]
  - weapon : Weapon
  - armor : Armor
  - potion : Potion
  + usePotion() : void
  + pickUpItem() : void
}

class Enemy {
  - reward : int
  - rank : int
  + giveMoney() : void
}

class Item {
  - name : string
  - value : int
}

class Weapon {
  - attackValue : int
}

class Armor {
  - defense : int
}

class Potion {
  - type : string
}

class Potion_HP {
  - healValue : int
}

class Potion_Strength {
  - buff : int
}

Room <|-- Room_Stage
Room <|-- Room_Shop
mob <|-- Player
mob <|-- Enemy
Player --> Item
Item <|-- Weapon
Item <|-- Armor
Item <|-- Potion
Potion <|-- Potion_HP
Potion <|-- Potion_Strength
@enduml