@startuml Physical View
title Deployment Diagram

node "Player Computer" {
  artifact "Game" {
    file "game.py"
    file "room.py"
    file "player.py"
    file "enemy.py"
    file "mob.py"
    file "item.py"
    file "monster.py"
  }
}

@enduml