@startuml Process View
title Sequence Diagram

actor Player

participant Game
participant Dungeon
participant Enemy
participant Shop

Player -> Game : main()/play_game()

loop [NUM_LEVELS]
  Game -> Shop : play_room(player)
  Shop -> Player : buy_items(items)

  Game -> Dungeon : play_room(player)
  Dungeon -> Enemy : choose random enemy

  loop [while enemy is alive]
    Dungeon -> Player : attack_entity(enemy)
    Dungeon -> Enemy : attack_entity(player)
  end

  Dungeon -> Player : add_money(reward)
end

Game -> Player : "Game Over!"

@enduml
